name: Auto Commit Bot

on:
  schedule:
    - cron: "0 */5 * * *"  
  workflow_dispatch:  

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 1  

      - name: Setup Git
        run: |
          git config --global user.name "IVerse-bot"
          git config --global user.email "178272406+IVerse@users.noreply.github.com"

      - name: Perubahan (biar bisa commit)
        run: |
          echo "Terakhir update: $(date)" > update.log
          git add update.log
          git commit -m "Auto update: $(date)" || echo "Tidak ada perubahan untuk commit"

      - name: Push perubahan ke repo dengan PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/IVerse-VDV/CyberVoid.git
          git push origin main

